### ISSUE TITLE
Agosto/2024: Sugestões de pauta

### ISSUE THREAD

**Issue by edilmedeiros** [poabitdevs/poabitdevs.org#1]
1Bi canais Ln/ano
https://x.com/peterktodd/status/1813928457946153056

Provas ZK verificadas no Bitcoin pela primeira vez
https://bitcoinmagazine.com/technical/a-zero-knowledge-proof-is-verified-on-bitcoin-for-the-first-time-in-history

Dream Team de Op_codes para o Roasbeef
https://x.com/roasbeef/status/1813658193631023416

TCP over Nostr
https://primal.net/e/note1uk728fkpgt8qqe2a9gylc9af5e4kjkyr05f3c04zpv8jgzwu9s6qpks74v

Anúncio PR Review club

**Comment by edilmedeiros** [comment]
Mudança na política de Disclosure do Core e 10 vulnerabilidades pré-0.21.0
https://x.com/darosior/status/1808489727730786365

Coleção de "Good First Issues" pra quem quer contribuir com FOSS Bitcoin
https://x.com/Bitcoin_Devs/status/1808170965999956280

Frost RFC
https://x.com/conradoplg/status/1808612054200373757

**Comment by axmbo** [comment]
MuSig é um protocolo para agregar chaves públicas e assinaturas para o algoritmo de assinatura digital Schnorr.
https://bitcoinops.org/en/topics/musig/

OP_CAT
https://medium.com/@dinodidthedash/op-cat-the-new-tapscript-opcode-that-can-help-make-bitcoin-magical-again-ae5959c23338

**Comment by edilmedeiros** [comment]
Carteira de Bitcoin da Proton
https://proton.me/blog/proton-wallet-launch
https://github.com/ProtonWallet/andromeda

**Comment by edilmedeiros** [comment]
A Bitaxe found a block
https://x.com/bitentrepreneur/status/1816173826754929125

**Comment by edilmedeiros** [comment]
BDK 1.0.0-beta.1
https://github.com/bitcoindevkit/bdk/releases/tag/v1.0.0-beta.1

**Comment by edilmedeiros** [comment]
Existe incentivo econômico em usar P2WSH ao invés de P2TR?
https://bitcoin.stackexchange.com/questions/123500/is-there-an-economic-incentive-to-use-p2wsh-over-p2tr

Bom tópico para iniciantes aprenderem que existem diferentes tipos de transações.

**Comment by edilmedeiros** [comment]
Por que os desevolvedores de protocolos trabalham para maximizar a receita dos mineradores?
https://bitcoin.stackexchange.com/questions/123679/why-do-protocol-developers-work-on-maximizing-miner-revenue

tl;dr não é para os mineradores, mas para os outros players da rede que não têm a mesma capacidade de prever os custos das transações.

**Comment by edilmedeiros** [comment]
Por que precisamos reestruturar a mempool para implementar o cluster mempool?
https://bitcoin.stackexchange.com/questions/123682/why-is-restructure-of-mempool-required-with-cluster-mempool

Mudanças de infraestrutura que parecem simples, mas são complexas.

O que é cluster mempool
https://bitcoinops.org/en/topics/cluster-mempool/

**Comment by viniciusfinger** [comment]
Assinatura de transações com Yubikey
https://vxtwitter.com/Nneuman/status/1816862638900658562

**Comment by edilmedeiros** [comment]
BIP draft for the FROST threshold signing protocol
https://groups.google.com/g/bitcoindev/c/PeMp2HQl-H4

**Comment by edilmedeiros** [comment]
Testnet 4 merged
https://github.com/bitcoin/bitcoin/pull/29775

**Comment by joaothallis** [comment]
Bitcoin scholarship da Chaincode
https://x.com/edil_medeiros/status/1820880740281938304?s=46
