### ISSUE TITLE
Setembro/2024: Sugestões de Pauta

### ISSUE THREAD

**Issue by edilmedeiros** [poabitdevs/poabitdevs.org#2]
Apple App Store censurando aplicativos de VPN (a mando do governo?)

https://x.com/protonvpn/status/1825181045035074016

**Comment by axmbo** [comment]
Pagamentos silenciosos aumentam a privacidade no Bitcoin, permitindo que o recebedor use um endereço público fixo, enquanto o remetente gera um endereço de pagamento exclusivo e secreto para cada transação. Isso faz com que cada transação seja única e não rastreável, preservando o anonimato do recebedor sem comprometer a praticidade.

https://plebs.substack.com/p/pagamentos-silenciosos

A dúvida é: que endereços são exibidos na blockchain? É possível identificar que vários desses pertencem ao mesmo possuidor, caso a carteira use diversas UTXOs como entrada de futuras transações?

Na matéria, fala que a identificação desses endereços na blockchain requer bastante processamento. Como funcionariam os scripts de entrada e saída, nesses casos?

**Comment by axmbo** [comment]
Output descriptors: 

https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

**Comment by edilmedeiros** [comment]
New Bitcoin Mining Development mailing list
https://groups.google.com/g/bitcoinminingdev

**Comment by edilmedeiros** [comment]
Did Segwit (BIP141) eliminate all txid malleability issues listed in BIP62?
https://bitcoin.stackexchange.com/a/124074

**Comment by edilmedeiros** [comment]
How can OP_CAT be used to implement additional covenants?
https://bitcoin.stackexchange.com/a/123829

**Comment by edilmedeiros** [comment]
Cool keys (Yubikey and Casa again)
https://blog.casa.io/cool-keys-security-model-for-bitcoin-and-yubikeys

**Comment by edilmedeiros** [comment]
Programa de capacitação da Vinteum
https://medium.com/vinteum-org/bitcoin-dev-launchpad-programa-de-aceleração-de-desenvolvedores-open-source-de-bitcoin-no-brasil-bfff58887153

**Comment by edilmedeiros** [comment]
Pauta em https://poabitdevs.org/2024-09-19-socratic-seminar-003
